Added : Home page
aiman-ansari/AiraveUI pull request #6
Opened 2022-02-17 18:29 UTC by aiman-ansari

![Screenshot (49)](https://user-images.githubusercontent.com/66882302/154665796-ce0a14df-433d-4120-b1a1-888364f09eac.png)

2022-02-17 21:36 UTC, PuneetP16 approved these changes

2022-02-17 21:36 UTC, PuneetP16 commented on index.css
> +    color:rgb(41, 41, 41);
use variables instead of direct values

2022-02-17 21:42 UTC, PuneetP16 commented
Screenshot is not uploaded, can you provide live preview link?

2022-02-17 21:46 UTC, PuneetP16 approved these changes

2022-02-18 10:08 UTC, manojsarna requested changes
Overall looks good!!

Do Check Comments

2022-02-18 10:08 UTC, manojsarna commented on index.css
> +    padding: 2rem 1rem;
can use font weight values, 500, 600 etc

2022-02-18 10:08 UTC, manojsarna commented on index.css
> +    .navbar{
63.5 or 62.5!!

do check your calculations

2022-02-18 10:08 UTC, manojsarna commented on index.html
> +            Made with <i class="fa fa-heart pd--5 text-secondary"></i> by Aiman Ansari
use Beautify to align your code

2022-02-18 13:32 UTC, sanu29 approved these changes
Neat and clean code looks good to merge

2022-02-18 13:34 UTC, merged